version: '3.7'
services:
  postgres-db:
    image: postgres:13.1-alpine
    container_name: quartz-scheduler-demo-postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: quartz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - quartz

networks:
  quartz:
    name: quartz
